apiVersion: maths.mydomain.com/v1
kind: Numericals
metadata:
  labels:
    app.kubernetes.io/name: numericals
    app.kubernetes.io/instance: numericals-sample
    app.kubernetes.io/part-of: myproject
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: myproject
  name: multiplication-1
spec:
  # TODO(user): Add fields here
  expression : "2*3"