# permissions for end users to view k8s-cronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-cronjob
    app.kubernetes.io/managed-by: kustomize
  name: k8s-cronjob-viewer-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - k8s-cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - k8s-cronjobs/status
  verbs:
  - get
